### Signup User
POST http://localhost:3000/auth/register
Content-Type: application/json
x-api-key: 750a405edc37cf32a4a16787cf9b08bc1957b732975f3204c2390f692a883dc9

{
  "email": "example@gmail.com",
  "password": "123456"
}

//yaminahouti@taptoplab.com

### Login User
POST http://localhost:3000/auth/login
Content-Type: application/json
x-api-key: 750a405edc37cf32a4a16787cf9b08bc1957b732975f3204c2390f692a883dc9

{
  "email": "example@gmail.com",
  "password": "123456"
}


### Create Habit
POST http://localhost:3000/habits
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZTE0NzQzZS04NzEzLTRlMzQtYjFkOC1kNzg0NWZlODU4OTQiLCJlbWFpbCI6ImV4YW1wbGVAZ21haWwuY29tIiwiaWF0IjoxNzU1NjAxNDUzLCJleHAiOjE3NTU2MDUwNTN9.F5k2jKjbfkVpAcq61TR2oxZSZFnP67AxafXv2If8iB4
x-api-key: 750a405edc37cf32a4a16787cf9b08bc1957b732975f3204c2390f692a883dc9

{
  "title": "Stay hyrated",
  "description": "Drink 8 of water everyday",
  "streak": 0,
  "frequency": "daily"
}

### Get All Habits
GET http://localhost:3000/habits
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZTE0NzQzZS04NzEzLTRlMzQtYjFkOC1kNzg0NWZlODU4OTQiLCJlbWFpbCI6ImV4YW1wbGVAZ21haWwuY29tIiwiaWF0IjoxNzU1NjAxNDUzLCJleHAiOjE3NTU2MDUwNTN9.F5k2jKjbfkVpAcq61TR2oxZSZFnP67AxafXv2If8iB4
x-api-key: 750a405edc37cf32a4a16787cf9b08bc1957b732975f3204c2390f692a883dc9


### COMPLETE HABIT
POST http://localhost:3000/habits/021fb54a-780f-4b1d-8bc2-b882dd5e0ea7/completions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZTE0NzQzZS04NzEzLTRlMzQtYjFkOC1kNzg0NWZlODU4OTQiLCJlbWFpbCI6ImV4YW1wbGVAZ21haWwuY29tIiwiaWF0IjoxNzU1NjAxNDUzLCJleHAiOjE3NTU2MDUwNTN9.F5k2jKjbfkVpAcq61TR2oxZSZFnP67AxafXv2If8iB4
x-api-key: 750a405edc37cf32a4a16787cf9b08bc1957b732975f3204c2390f692a883dc9


### Get Single Habit
GET http://localhost:3000/habits/43469613-51f7-4c3a-9bbe-134d7068b439
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZTE0NzQzZS04NzEzLTRlMzQtYjFkOC1kNzg0NWZlODU4OTQiLCJlbWFpbCI6ImV4YW1wbGVAZ21haWwuY29tIiwiaWF0IjoxNzU1NjAxNDUzLCJleHAiOjE3NTU2MDUwNTN9.F5k2jKjbfkVpAcq61TR2oxZSZFnP67AxafXv2If8iB4
x-api-key: 750a405edc37cf32a4a16787cf9b08bc1957b732975f3204c2390f692a883dc9

### Update Habit
PATCH http://localhost:3000/habits/43469613-51f7-4c3a-9bbe-134d7068b439
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZTE0NzQzZS04NzEzLTRlMzQtYjFkOC1kNzg0NWZlODU4OTQiLCJlbWFpbCI6ImV4YW1wbGVAZ21haWwuY29tIiwiaWF0IjoxNzU1NjAxNDUzLCJleHAiOjE3NTU2MDUwNTN9.F5k2jKjbfkVpAcq61TR2oxZSZFnP67AxafXv2If8iB4
x-api-key: 750a405edc37cf32a4a16787cf9b08bc1957b732975f3204c2390f692a883dc9

{
  "title": "Evening Squats",
  "description": "20 squats every evening",
  "last_completed": "2025-08-16T00:00:00.000Z",
  "streak": 2
}

### Delete Habit
DELETE http://localhost:3000/habits/7ed42a36-9da1-48b6-86f4-53fa2280d065
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZTE0NzQzZS04NzEzLTRlMzQtYjFkOC1kNzg0NWZlODU4OTQiLCJlbWFpbCI6ImV4YW1wbGVAZ21haWwuY29tIiwiaWF0IjoxNzU1NjAxNDUzLCJleHAiOjE3NTU2MDUwNTN9.F5k2jKjbfkVpAcq61TR2oxZSZFnP67AxafXv2If8iB4
x-api-key: 750a405edc37cf32a4a16787cf9b08bc1957b732975f3204c2390f692a883dc9
